print("welcomr to the calculators of s.s.s.")
a=int(input ("input the valvue of a"))
b=int(input("input the value of b"))
print((a+b))
print((a-b))
print((a/b))
print((a*b))
print((a//b))
print((a**b))
print((a%b))
