print("to check person is pass orr fail")
marks=float(input("tell your marks")
if(marks>33)
        print("you are pass")
        print("you can study next class")
        print("study in vj collage")
else:(fail)
        print("you are fail",marks<33)
        print("go and study")           
